server:
  port: 8080
spring:
  application:
    name: "appbank"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://admindb:L4dIAnsdqSuqWxAz@cluster0.hrhqtf6.mongodb.net/test"
rabbitmq:
        host: "localhost"
        username: "guest"
        password: "guest"
        virtual_host:
        port: 15672
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
